### ISSUE TITLE
react-native-vector-icons dependency error

### ISSUE THREAD

**Issue by ezhkov** [srk-sharingan/sharingan-rn-modal-dropdown#23]
Thank you for great component! 

When I try to start my project with your component, I have following error:
`Error: Unable to resolve module 'react-native-vector-icons/MaterialCommunityIcons' from 'node_modules/sharingan-rn-modal-dropdown/src/Components/Item.tsx': react-native-vector-icons/MaterialCommunityIcons could not be found within the project.`

Some components of your Dropdown have `react-native-vector-icons` as dependency. I looked into code and noticed, that
there is only one icon imported from that library — check icon. I have my custom SVG library in my project and it would be great not to install such big dependency as `react-native-vector-icons`. Can you make this single icon to be an SVG or maybe there is a way to allow user set his own icon component?

**Comment by srk-sharingan** [comment]
Hello, @ezhkov thanks for the information.
I've developed this component by keeping the **react-native-paper** in mind. I think the native paper expecting the vector-icons.
Even, If I remove the dependencies still, you will end up installing **react-native-paper** to make this component work. Because a lot of components are shared from **react-native-paper** to this component. :)

**Comment by ezhkov** [comment]
Thank you for answer. The thing is I have `react-native-paper` installed in my project and use `babel-plugin-optional-require` with `FontAwesome` icons to put only needed icons to bundle. But I think you right. I put `react-native-paper` into app to make it more native-look, so change icons system sounds logical)
