### ISSUE TITLE
Dropdown won't pop on the bottom of the container

### ISSUE THREAD

**Issue by vai-everton** [srk-sharingan/sharingan-rn-modal-dropdown#25]
Currently facing this issue with the picker, I'm trying to simply put the modal in the bottom of the container, but it keeps popping in this random location.

![bug-report](https://user-images.githubusercontent.com/69922518/113209481-1f43d200-9241-11eb-8f26-ae71709b79ea.png)

**Comment by srk-sharingan** [comment]
This happens because the dropdown modal tries to not open the model below the viewport. When it tries calculating the position of the dropdown it's too bottom to show the model, hence this behavior.
Currently, I don't have any fix for this maybe you can make the dropdown **floating**, but that still opens the dropdown separate but at least opens at the proper location (at the top).
